import { globalStyles } from './global.styles';
import { getCssText } from './stitches.config';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles()
  
  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{__html: getCssText()}}></style>
      </head>
      <body>{children}</body>
    </html>
  );
}
