import { SessionProvider } from '@components/session-provider';
import { darkTheme } from '@styles/dark-theme';
import { globalStyles } from '@styles/global.styles';
import { getCssText } from '@styles/stitches.config';
import { getServerSession } from 'next-auth';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();

  const session = await getServerSession();

  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        ></style>
      </head>
      <body>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
